spring:
  application:
    name: ZuulApiGateway
server:
    port: 8762
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
 
zuul:
    
    routes:
        userservice:
            path: /zuuluser/**
            serviceId: UserService
        noteservice:
            path: /zuulnotes/**
            serviceId: NoteService  
             